### ISSUE TITLE
Screenshot managers opens with media keys if no keybind is set

### ISSUE THREAD

**Issue by Syandriel** [LGatodu47/ScreenshotViewer#10]
I'm currently playing the TMP Limitless 6 Pack for Forge 1.19.2.

When I use the media keys on my keyboard, the screenshot manager opens, event tho no keybinds are set to open the screenshot manager. When I set a keybind the screenshot manager does not open with the media keys.

I'm using the Logitech G815. This could also be a bug in the Logitech G HUB software.

**Comment by LGatodu47** [comment]
Hello, thank you for opening an issue.

Regarding this one it probably comes from the Logitech G HUB software as you implied or something else. By default, the screenshot manager keybinding is mapped as every undefined keybinding to an "Unknown Keybinding" with code -1.
When you're using media keys, GLFW (library that interprets inputs) probably doesn't recognize the key you pressed and just assumes you pressed a key with code -1, leading to the screenshot manager opening. However, I don't know why exactly the screenshot manager opens and not something else (as multiple controls are assigned to an "Unknown Keybinding", especially on modpacks).

I'm closing this issue, I'll try to fix it for the next Minecraft versions, and I might also try for Minecraft on Forge 1.19x.
