### ISSUE TITLE
[1.20.1] Crash when booting game.

### ISSUE THREAD

**Issue by Gbergz** [LGatodu47/ScreenshotViewer#12]
Title^

MC: 1.20.1
Forge: 47.1.0
Screenshot Viewer: 1.1.5

Logs (no crash report generated): https://gist.githubusercontent.com/Gbergz/e2b394fc4b68579711a7afe916ad0c29/raw/6a3d295dac37e41d8ca0397aeda761fe8c8d7c57/gistfile1.txt

**Comment by LGatodu47** [comment]
Thanks, reuploaded the version with a fix on CurseForge and Modrinth.
