### ISSUE TITLE
Pause Menu Placement

### ISSUE THREAD

**Issue by badooga** [LGatodu47/ScreenshotViewer#16]
Hi there, the mod looks sick! I'm interested in using it, although I'm a little put off by its position on the pause menu. While its position can be adjusted there, I was wondering if it'd be possible to add a config option that adds it as a regular button, just like how Mod Menu adds a `Mods` button alongside `Advancements`, `Options`, and so on. If not, perhaps an option to move it to the `Options` menu so that it is out of sight?

This isn't a deal breaker of course, so either way, thank you for making this!

**Comment by LGatodu47** [comment]
Hello, adressing a few things you said here:

> I was wondering if it'd be possible to add a config option that adds it as a regular button

Well it is possible, however I would say it isn't very "conventional" to add it as a regular button. It would make the pause menu overflow for users on low resolution screens, especially if every mod started doing this.

> If not, perhaps an option to move it to the `Options` menu so that it is out of sight?

In my opinion, moving the button to the `Options` menu seems irrelevant (it wouldn't be coherent), and you can always hide the button in the pause menu with the config option `show_button_in_game_pause_menu`.

Anyways, I'm know that this answer doesn't seem very helpful, but I sadly can't comply with everyone's preferences when making the mod. Besides from that, I'm glad to see that you enjoy the mod, and I thank you for your feedback!
