### ISSUE TITLE
Screenshot Chat Text

### ISSUE THREAD

**Issue by badooga** [LGatodu47/ScreenshotViewer#17]
When taking a screenshot, the game tells you `Saved screenshot as ...` in the chat, where the file name links to the file on your computer. Would it be possible to replace this file link with a link that brings you to the Screenshot Manager directly?

**Comment by LGatodu47** [comment]
It is an interesting idea, however I'm not sure everyone would like this behaviour, so it will probably be toggleable in the mod config if I implement it.

**Comment by LGatodu47** [comment]
Implemented in Screenshot Viewer 1.2.0
