### ISSUE TITLE
⚠️[Bug] Screenshots not showing up in the gallery

### ISSUE THREAD

**Issue by User4716** [LGatodu47/ScreenshotViewer#18]
I use a mod called SharedResources (https://modrinth.com/mod/shared-resources) which can make it so that you can have the same worlds, screenshots, resource packs, and everything across multiple modpacks. 

And it does that by simply changing the directory of those specific things to a global one 
(For example, all screenshots for one profile will be stored in a global folder where all of my modpacks can access the same screenshots if the mod is installed on those modpacks, and the same for the worlds and resource packs, etc.)

And that is the reason why this mod doesn't show my screenshots in my library/gallery because the screenshots are stored in a different location than the default one, **and to fix this you simply need to add an option to change the screenshots folder that this mod will use!** 😉

**Comment by LGatodu47** [comment]
Hello,

I was away for some time and I couldn't adress this earlier, but first, I'd like to thank you for introducing me to this mod. I feel it can be very useful especially for those who play on a lot of different instances of Minecraft (with MultiMC for example).

Regarding your issue, I'm currently working on a new version of the mod which will include, as you say, "an option to change the screenshots folder". It should release soon (today if I finish it or in a few days), so I hope it will help.

**Comment by User4716** [comment]
Alright, I'm glad you are actually making this idea to reality 😉😊
Thank you :)

**Comment by LGatodu47** [comment]
Fixed in Screenshot Viewer 1.2.0 :)
