### ISSUE TITLE
scroll area isn't working correctly

### ISSUE THREAD

**Issue by ISteam14** [LGatodu47/ScreenshotViewer#19]
Scroll doesn't work if you drag it with the mouse.

I don’t know if the author of the mod added such a function at all, but I would like it to work

Video not as useful because mouse clicks are not visible, but I'll be glad if it helps

https://github.com/LGatodu47/ScreenshotViewer/assets/91954858/ab9c9e8c-2d4c-4721-b784-2d6985aa2414

**Comment by LGatodu47** [comment]
Hi,

To be honest, the reason you can't drag to scroll is simply because I was lazy when I designed this scrollbar (it was also the first time I tried designing one by myself). I'm currently working on the next version of the mod and I'll try to get this implemented.

**Comment by LGatodu47** [comment]
Fixed in Screenshot Viewer 1.2.0!
