### ISSUE TITLE
Incompatibility with FPS Reducer

### ISSUE THREAD

**Issue by ViTulyankin** [LGatodu47/ScreenshotViewer#2]
Crash logs:
https://crashy.net/sSVa1EAEFULTnlMVePsX

**Comment by LGatodu47** [comment]
Thanks for submitting. The crash had nothing to do with FPS Reducer but with Better Recipe Books I believe. It should now be fixed in the 1.1.2 version for Minecraft 1.19.2.

**Comment by ViTulyankin** [comment]
Huh, strange. If it was incompatibilities with FPS Reducer, I could understand it, especially considering that Not Enough Crashes said:
![Снимок экрана 2022-12-10 010918](https://user-images.githubusercontent.com/92220631/206788249-a837d553-c325-4d58-972b-956792eca3ec.png)

But Better Recipe Books... That's really odd for me.
I'm glad that it will be fixed soon :)
