### ISSUE TITLE
please make it so that it is in order

### ISSUE THREAD

**Issue by the-biggest-birfd** [LGatodu47/ScreenshotViewer#22]
this is bad. very bad.
<img width="2503" alt="Screenshot 2023-11-04 at 22 25 26" src="https://github.com/LGatodu47/ScreenshotViewer/assets/132025093/8226aeea-1b5c-4a2b-9019-6d56b43baacc">
please fix

**Comment by LGatodu47** [comment]
Will be fixed in the next mod version
