### ISSUE TITLE
Feature: disable display of screenshot names 

### ISSUE THREAD

**Issue by Felisinnn** [LGatodu47/ScreenshotViewer#24]
I think it would just look much cleaner and doesn't sound too complicated to implement (no idea though). Maybe the names could show up only when you hover over the image, for instance.

**Comment by LGatodu47** [comment]
Alright I'll try to implement this one in the next mod version 👍

**Comment by LGatodu47** [comment]
Most recent versions now have an option called "Screenshot Names Visibility". When set on HIDDEN, the names won't display anymore. Although I think this requires more work because the space below the screenshots for the names is still there. I'm leaving this one opened.

**Comment by LGatodu47** [comment]
Closing this one now as I fixed the problem in the latest commit.
