### ISSUE TITLE
Resourcepack support

### ISSUE THREAD

**Issue by PSYCHEER** [LGatodu47/ScreenshotViewer#25]
Hi there! I'm making modpack for server and I'm using resourcepacks, but just button "Screenshot manager" wasn't changed, so I mean, it's not button as background and foreground image but it's just whole image, it's some chance to make it resourcepack-comaptible?

**Comment by PSYCHEER** [comment]
![image](https://github.com/LGatodu47/ScreenshotViewer/assets/42911029/1978a530-375a-4339-a91b-5dee89c06f1c)

**Comment by LGatodu47** [comment]
I'm not sure if I can fix that through my mod, I'll try my best. However as a temporary solution or if I can't fix it, you can make custom textures for the button and include it in your ressource pack, and put them in `assets/screenshot_viewer/textures/sprites/widget`. Be careful to name them correctly (i.e. `screenshots_button.png` and `screenshots_button_focused.png`). Anyways I hope this could help.

**Comment by LGatodu47** [comment]
See #29, but I found a way to fix this. I'm closing this one too.
