### ISSUE TITLE
Zooming in works the wrong way

### ISSUE THREAD

**Issue by Mideks** [LGatodu47/ScreenshotViewer#27]
When I use ctrl + mouse wheel, I expect the zoom to increase when I scroll the wheel forward and decrease when I scroll the wheel backward. However, everything is exactly the opposite.
I suggest either correcting this misunderstanding, or providing a setting that would allow you to choose the necessary behavior.

**Comment by LGatodu47** [comment]
There's a new config option in the latest version to change this behaviour. I'm therefore closing this issue.
