### ISSUE TITLE
1.20.3-4 support

### ISSUE THREAD

**Issue by ViTulyankin** [LGatodu47/ScreenshotViewer#28]
Game launches, but crashes when openning screenshot GUI. I really love this mod and hope you will update it someday to the newest versions of Minecraft

**Comment by SA64BD** [comment]
bump

**Comment by dimkakartinka** [comment]
ну как всегда нету русских

**Comment by WildFyr16** [comment]
I am going to take a look at the crash log to see if I can find out why it is crashing, because it seems to load correctly (as in all screenshots populate and for the few seconds before crash you can see them)

**Comment by sternschnaube** [comment]
Latest version loads fine on 1.20.2, but if I click on the settings button >>>

**Comment by LGatodu47** [comment]
Support for 1.20.4 is available on Fabric. Forge will come soon.

**Comment by sternschnaube** [comment]
Thank you!! 😊
