### ISSUE TITLE
[Compatibility] Resource Packs

### ISSUE THREAD

**Issue by QwertRvg** [LGatodu47/ScreenshotViewer#29]
If a Resource Pack that changes the menu buttons alongside the mod it feels- off
It would be nice if the Menu Button used the menu button textures used by a Resource Pack.

![image](https://github.com/LGatodu47/ScreenshotViewer/assets/89683173/64c4217f-5316-48c5-a8ae-149cd3aa1778)
here is the Menu Button next to the Reimagined UI Resource Pack
(the icons are added by a different pack, they arent important here)

**Comment by HB-Stratos** [comment]
I would appreciate a backport of this fix to 1.20.1 as this is the current main modding version and the version I am developing a modpack with custom menu texture pack in.
