### ISSUE TITLE
Screenshot Viewer cant show screenshots on symlinks

### ISSUE THREAD

**Issue by Djihads1** [LGatodu47/ScreenshotViewer#36]
i have been playing with this mod for a good while and it is a really good mod
recently tho, i wanted to try the Better MC modpack, but my computer is weak so i decided to go on linux and play there
since i dont always use linux, i decided to make the screenshot folder a symlink to the one in windows (because windows cant read ext3/ext4 partitions and therefor i cant access my screenshots on windows)

the screenshots are saved fine, but screenshot viewer says there are no screenshots

**Comment by LGatodu47** [comment]
Hello,
It is quite complicated to replicate your issue and as I tested, it seems that Screenshot Viewer doesn't have much issues when reading symlinks. Make sure the path to your symlink specified in the mod config is correct and is accessible and readable.
I can't bring further help so I'm closing this.
