### ISSUE TITLE
Add option to copy to clipboard

### ISSUE THREAD

**Issue by EltoCode** [LGatodu47/ScreenshotViewer#4]
When viewing or right clicking on a screenshot, add an option to copy the screenshot to keyboard. 

Currently, to copy to clipboard, you have to open the screenshot with an external photo editor first, and then copy. It would be nice if it were streamlined.

**Comment by LGatodu47** [comment]
Might add this in the next version of the mod. Thanks for the suggestion!

**Comment by LGatodu47** [comment]
Fixed in the latest version of the mod (1.1.5 on mc 1.19.4 for fabric only). Will port this to 1.19.3
