### ISSUE TITLE
[1.19.3] Crash when opening the gallery while a screenshot is being written to

### ISSUE THREAD

**Issue by newtykins** [LGatodu47/ScreenshotViewer#6]
I use Fabrishot to take high resolution screenshots, and thus there is a lot of data to write to the files. If you try and open the gallery while this data is being written, the game crashes. Perhaps this could be prevented? You can see the crash error below (ignore my screenshot border, I can't be bothered to turn it off :P)

![image](https://user-images.githubusercontent.com/19301186/222975980-c56cd30a-7873-4ece-ab86-05dd9829ae84.png)

**Comment by LGatodu47** [comment]
Thanks for the submission. I just fixed that crash in the latest version of the mod (1.1.4) for fabric on 1.19.3. The game won't crash anymore, the image(s) that fail to load will just appear unloaded.
