### ISSUE TITLE
Mis-aligned menu icon + add a hotkey to open the menu

### ISSUE THREAD

**Issue by Scarlaid** [LGatodu47/ScreenshotViewer#9]
Finally I found this as a Nicephore alternative, but I do find an issue with this
- The menu icon being offset 
- No hotkey to open the menu as far as I have searched

Would be fantastic if a hotkey was added because it's kinda a hassle to open the menu just for the screenshot

![image](https://github.com/LGatodu47/ScreenshotViewer/assets/90851437/ffc8d889-d657-4807-93f2-b1a85d4be462)

**Comment by LGatodu47** [comment]
Hello, regarding your issues:

> The menu icon being offset

This is the spacing I sticked with when making the mod. I might actually change it so it aligns better with other mod's buttons. As a temporary solution I suggest you disable this button in the mod config (especially if you count on using the hotkey).

> No hotkey to open the menu as far as I have searched

There is actually a keybinding for the screenshot menu, in the "Miscellaneous" section.
![image](https://github.com/LGatodu47/ScreenshotViewer/assets/62804774/75c03068-d70e-407b-8ce0-6973054464a6)

I hope my answer could help you.

**Comment by hschwar** [comment]
Are there still plans for changing the mod button spacing?
